name: Trigger Vercel Order Window Function

on:
  schedule:
    - cron: '59 3 * * *'  # 3:59 AM UTC = 11:59 PM EDT
  workflow_dispatch:      # Also allows manual run from GitHub UI

jobs:
  call-vercel-function:
    runs-on: ubuntu-latest

    steps:
      - name: Call Vercel Serverless Function
        run: |
          curl -s -X GET "https://hocky-name-generator-seven.vercel.app/api/updateInventoryPolicy"